- name: Install zsh
  become: true
  ansible.builtin.package:
    name:
      - zsh
  tags: zsh

- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh)
  tags: zsh

- name: Check that oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_stats
  tags: zsh

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer --keep-zshrc
  when: oh_my_stats.stat.exists == False
  tags: zsh

- name: Configure .zshrc
  ansible.builtin.copy:
    src: home/.zshrc
    dest: ~/.zshrc
    mode: "0644"
  tags: zsh

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: zsh
